/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ykspuan;

import javax.swing.JOptionPane;

/**
 *
 * @author Irem
 */
public class yksPuanHesapla extends javax.swing.JFrame {

    /**
     * Creates new form yksPuanHesapla
     */
    public yksPuanHesapla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tyt3 = new javax.swing.JTextField();
        tyt6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tyt5 = new javax.swing.JTextField();
        tyt7 = new javax.swing.JTextField();
        tyt8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tyt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tyt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tyt4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sos2 = new javax.swing.JTextField();
        sos1 = new javax.swing.JTextField();
        sos3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sos4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        sos5 = new javax.swing.JTextField();
        sos6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sos8 = new javax.swing.JTextField();
        sos10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sos7 = new javax.swing.JTextField();
        sos9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sos11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        sos12 = new javax.swing.JTextField();
        sos13 = new javax.swing.JTextField();
        sos14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mat1 = new javax.swing.JTextField();
        mat2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fen2 = new javax.swing.JTextField();
        fen1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        fen3 = new javax.swing.JTextField();
        fen4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        fen6 = new javax.swing.JTextField();
        fen5 = new javax.swing.JTextField();
        dil1 = new javax.swing.JTextField();
        dil2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tm_puan = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        soz_puan = new javax.swing.JTextField();
        say_puan = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        dil_puan = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        dipNot = new javax.swing.JTextField();
        m_hesapla = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tyt_puan = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tytTopNet = new javax.swing.JLabel();
        m_goster1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        topSos1Net = new javax.swing.JLabel();
        m_goster2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        topSos2Net = new javax.swing.JLabel();
        m_goster3 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        topMat2Net = new javax.swing.JLabel();
        m_goster4 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        topFen2Net = new javax.swing.JLabel();
        m_goster5 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        topDilNet = new javax.swing.JLabel();
        m_goster6 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Üniversite Yerleştirme Puanı Hesapla");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tyt3.setText("0");
        getContentPane().add(tyt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 37, -1));

        tyt6.setText("0");
        getContentPane().add(tyt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 37, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setText("Sosyal Bilimler");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        tyt5.setText("0");
        tyt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyt5ActionPerformed(evt);
            }
        });
        getContentPane().add(tyt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 37, -1));

        tyt7.setText("0");
        getContentPane().add(tyt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 37, -1));

        tyt8.setText("0");
        getContentPane().add(tyt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 37, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setText("Yanlış");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, -1));

        tyt1.setText("0");
        tyt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyt1ActionPerformed(evt);
            }
        });
        getContentPane().add(tyt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 37, -1));

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        jLabel1.setText("TYT SINAVI (YKS 1.OTURUM)");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 20));

        tyt2.setText("0");
        tyt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyt2ActionPerformed(evt);
            }
        });
        getContentPane().add(tyt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 37, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setText("Türkçe");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setText("Doğru");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 37, -1));

        tyt4.setText("0");
        tyt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyt4ActionPerformed(evt);
            }
        });
        getContentPane().add(tyt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 37, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setText("Fen Bilimleri");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 78, -1));

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        jLabel9.setText("AYT SINAVI (YKS 2.OTURUM)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 20));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel10.setText("TÜRK DILI ve EDEBIYATI / SOSYAL BILIMLER-1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 260, 20));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel11.setText("Doğru");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 40, 20));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel12.setText("Yanlış");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 40, 20));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel14.setText("Türk Dili ve Edebiyat");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 30));

        sos2.setText("0");
        sos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sos2ActionPerformed(evt);
            }
        });
        getContentPane().add(sos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 37, 30));

        sos1.setText("0");
        sos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sos1ActionPerformed(evt);
            }
        });
        getContentPane().add(sos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 40, 30));

        sos3.setText("0");
        getContentPane().add(sos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 37, 30));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel15.setText("Tarih-1");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 43, -1));

        sos4.setText("0");
        getContentPane().add(sos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 37, 30));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel16.setText("Coğrafya-1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        sos5.setText("0");
        getContentPane().add(sos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 36, 30));

        sos6.setText("0");
        getContentPane().add(sos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 38, 30));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel17.setText("SOSYAL BİLİMLER 2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 141, -1));

        sos8.setText("0");
        getContentPane().add(sos8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 37, -1));

        sos10.setText("0");
        getContentPane().add(sos10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 37, -1));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel18.setText("Tarih-2");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 43, -1));

        sos7.setText("0");
        sos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sos7ActionPerformed(evt);
            }
        });
        getContentPane().add(sos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 37, -1));

        sos9.setText("0");
        getContentPane().add(sos9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 37, -1));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel19.setText("Coğrafya-2");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        sos11.setText("0");
        getContentPane().add(sos11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 37, -1));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel20.setText("Felsefe Grubu");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        sos12.setText("0");
        getContentPane().add(sos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 37, -1));

        sos13.setText("0");
        getContentPane().add(sos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 37, -1));

        sos14.setText("0");
        sos14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sos14ActionPerformed(evt);
            }
        });
        getContentPane().add(sos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 37, -1));

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel21.setText("Din Kültürü");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 60, -1));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel22.setText("MATEMATİK  2");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 90, -1));

        mat1.setText("0");
        getContentPane().add(mat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 37, -1));

        mat2.setText("0");
        getContentPane().add(mat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 37, -1));

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel23.setText("Matematik");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel24.setText("FEN BİLİMLERİ  2");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 103, -1));

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel25.setText("Fizik ");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 40, -1));

        fen2.setText("0");
        fen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fen2ActionPerformed(evt);
            }
        });
        getContentPane().add(fen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 37, -1));

        fen1.setText("0");
        getContentPane().add(fen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 37, -1));

        jLabel26.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel26.setText("Kimya");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 43, -1));

        fen3.setText("0");
        getContentPane().add(fen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 37, -1));

        fen4.setText("0");
        fen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fen4ActionPerformed(evt);
            }
        });
        getContentPane().add(fen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 37, -1));

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel27.setText("Biyoloji");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 43, -1));

        fen6.setText("0");
        fen6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fen6ActionPerformed(evt);
            }
        });
        getContentPane().add(fen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 37, -1));

        fen5.setText("0");
        getContentPane().add(fen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 37, -1));

        dil1.setText("0");
        getContentPane().add(dil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 37, -1));

        dil2.setText("0");
        getContentPane().add(dil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 37, -1));

        jLabel28.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        jLabel28.setText("YKS YABANCI DIL SINAVI");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 160, -1));

        jLabel29.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel29.setText("Doğru");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 37, -1));

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel30.setText("Yanlış");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 40, -1));

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel32.setText("Dil");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 43, -1));

        jLabel34.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel34.setText("Eşit Ağırlık");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 60, 20));

        tm_puan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm_puanActionPerformed(evt);
            }
        });
        getContentPane().add(tm_puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 180, -1));

        jLabel39.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel39.setText("Sözel");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 60, 20));

        soz_puan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soz_puanActionPerformed(evt);
            }
        });
        getContentPane().add(soz_puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 180, -1));

        say_puan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                say_puanActionPerformed(evt);
            }
        });
        getContentPane().add(say_puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 180, -1));

        jLabel40.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel40.setText("Sayısal");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 60, 20));

        jLabel41.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel41.setText("Dil");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 60, 20));

        dil_puan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dil_puanActionPerformed(evt);
            }
        });
        getContentPane().add(dil_puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 180, -1));

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel33.setText("Diploma Notu: ");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 100, 30));
        getContentPane().add(dipNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 82, -1));

        m_hesapla.setText("HESAPLA");
        m_hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_hesaplaActionPerformed(evt);
            }
        });
        getContentPane().add(m_hesapla, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 89, 30));

        jLabel35.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel35.setText("PUAN TİPİ");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        jLabel37.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel37.setText("YERLEŞTİRME PUANI");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 150, -1));

        jLabel38.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel38.setText("TYT Puanı");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 60, -1));

        tyt_puan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyt_puanActionPerformed(evt);
            }
        });
        getContentPane().add(tyt_puan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 180, -1));

        jLabel36.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel36.setText("Matematik");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setText("Toplam Net:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 20));

        tytTopNet.setText("0");
        getContentPane().add(tytTopNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 40, 20));

        m_goster1.setText("GÖSTER");
        m_goster1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_goster1ActionPerformed(evt);
            }
        });
        getContentPane().add(m_goster1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 20));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setText("Toplam  Net:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 70, 20));

        topSos1Net.setText("0");
        getContentPane().add(topSos1Net, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 40, 20));

        m_goster2.setText("GÖSTER");
        m_goster2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_goster2ActionPerformed(evt);
            }
        });
        getContentPane().add(m_goster2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 100, 20));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel13.setText("Toplam  Net:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 80, -1));

        topSos2Net.setText("0");
        getContentPane().add(topSos2Net, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 40, -1));

        m_goster3.setText("GÖSTER");
        m_goster3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_goster3ActionPerformed(evt);
            }
        });
        getContentPane().add(m_goster3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 100, 20));

        jLabel42.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel42.setText("Yanlış");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 40, -1));

        jLabel43.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel43.setText("Doğru");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 37, -1));

        jLabel44.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel44.setText("Doğru");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 50, -1));

        jLabel45.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel45.setText("Yanlış");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 40, -1));

        jLabel46.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel46.setText("Toplam  Net:");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 80, -1));

        topMat2Net.setText("0");
        getContentPane().add(topMat2Net, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 40, -1));

        m_goster4.setText("GÖSTER");
        m_goster4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_goster4ActionPerformed(evt);
            }
        });
        getContentPane().add(m_goster4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 100, 20));

        jLabel47.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel47.setText("Toplam  Net:");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 80, -1));

        topFen2Net.setText("0");
        getContentPane().add(topFen2Net, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 40, -1));

        m_goster5.setText("GÖSTER");
        m_goster5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_goster5ActionPerformed(evt);
            }
        });
        getContentPane().add(m_goster5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 100, 20));

        jLabel48.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel48.setText("Doğru");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 37, -1));

        jLabel49.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel49.setText("Yanlış");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 40, -1));

        jLabel50.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel50.setText("Toplam  Net:");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 80, -1));

        topDilNet.setText("0");
        getContentPane().add(topDilNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 40, -1));

        m_goster6.setText("GÖSTER");
        m_goster6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_goster6ActionPerformed(evt);
            }
        });
        getContentPane().add(m_goster6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 100, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/download.png"))); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 270, 120));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/afXAEH.jpg"))); // NOI18N
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 270, 250));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/images.jpg"))); // NOI18N
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 270, 280));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/olpLvG.jpg"))); // NOI18N
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 290, 150));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/9c5816cb341ef96457e0bc99c6d99e18.jpg"))); // NOI18N
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 290, 290));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/one-colour-solid-color-plain-pink-single-2200x2480-c-fcbcd7-f-24.jpg"))); // NOI18N
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 290, 70));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/9c5816cb341ef96457e0bc99c6d99e18.jpg"))); // NOI18N
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 290, 300));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/one-colour-solid-color-plain-pink-single-2200x2480-c-fcbcd7-f-24.jpg"))); // NOI18N
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, 260));

        jLabel53.setBackground(new java.awt.Color(255, 102, 0));
        jLabel53.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        jLabel53.setText("TYT SINAVI (YKS 1.OTURUM)");
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel53.setFocusable(false);
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 20));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ykspuan/480536.jpg"))); // NOI18N
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1100, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tyt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyt5ActionPerformed

    private void tyt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyt1ActionPerformed

    private void tyt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyt2ActionPerformed

    private void tyt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyt4ActionPerformed

    private void sos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sos2ActionPerformed

    }//GEN-LAST:event_sos2ActionPerformed

    private void sos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sos1ActionPerformed

    private void sos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sos7ActionPerformed

    }//GEN-LAST:event_sos7ActionPerformed

    private void sos14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sos14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sos14ActionPerformed

    private void fen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fen2ActionPerformed

    private void fen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fen4ActionPerformed

    }//GEN-LAST:event_fen4ActionPerformed

    private void fen6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fen6ActionPerformed

    }//GEN-LAST:event_fen6ActionPerformed

    private void tm_puanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm_puanActionPerformed
        tm_puan.setEditable(false);
    }//GEN-LAST:event_tm_puanActionPerformed

    private void soz_puanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soz_puanActionPerformed
        soz_puan.setEditable(false);
    }//GEN-LAST:event_soz_puanActionPerformed

    private void say_puanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_say_puanActionPerformed
        say_puan.setEditable(false);
    }//GEN-LAST:event_say_puanActionPerformed

    private void dil_puanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dil_puanActionPerformed
        dil_puan.setEditable(false);
    }//GEN-LAST:event_dil_puanActionPerformed

    private void m_hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_hesaplaActionPerformed
        try{

            double obp=0;
            if(Double.parseDouble(dipNot.getText())<0 || Double.parseDouble(dipNot.getText())>100)
            throw new ArithmeticException("Lütfen diploma notunu 0 ile 100 arası değer giriniz!");
            else
            obp=Double.parseDouble(dipNot.getText())*0.6;

            double tytToplam=Double.parseDouble(tytTopNet.getText());
            double tytPuan=100+obp+(tytToplam*3.33);

            double tmToplam=Double.parseDouble(topSos1Net.getText())+Double.parseDouble(topSos2Net.getText())+Double.parseDouble(topMat2Net.getText());
            double ayt_tm=100+obp+(tytToplam*1.33)+(tmToplam*3);

            double sozToplam=Double.parseDouble(topSos1Net.getText())+Double.parseDouble(topSos2Net.getText());
            double ayt_soz=100+obp+(tytToplam*1.33)+(sozToplam*3);

            double sayToplam=Double.parseDouble(topMat2Net.getText())+Double.parseDouble(topFen2Net.getText());
            double ayt_say=100+obp+(tytToplam*1.33)+(sayToplam*3);

            double ayt_dil=100+obp+(tytToplam*1.33)+(Double.parseDouble(topDilNet.getText())*3);

            tyt_puan.setText(String.valueOf(tytPuan));
            tm_puan.setText(String.valueOf(ayt_tm));
            soz_puan.setText(String.valueOf(ayt_soz));
            say_puan.setText(String.valueOf(ayt_say));
            dil_puan.setText(String.valueOf(ayt_dil));
        }
        catch(ArithmeticException e){

            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_m_hesaplaActionPerformed

    private void tyt_puanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyt_puanActionPerformed
        tyt_puan.setEditable(false);
    }//GEN-LAST:event_tyt_puanActionPerformed

    private void m_goster1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_goster1ActionPerformed
        try{

            double d_1=Double.parseDouble(tyt1.getText());
            double y_1=Double.parseDouble(tyt2.getText());

            double net_1=0;
            if(d_1+y_1>40)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türkçe 40 soru\n"+
                "Matematik 40 soru \n"+"Sosyal Bilimler 20 soru\n"+
                "Fen Bilimleri 20 soru\n");
            else
            net_1=d_1-(y_1/4);

            double d_2=Double.parseDouble(tyt3.getText());
            double y_2=Double.parseDouble(tyt4.getText());

            double net_2=0;
            if(d_2+y_2>40)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türkçe 40 soru\n"+
                "Matematik 40 soru \n"+"Sosyal Bilimler 20 soru\n"+
                "Fen Bilimleri 20 soru\n");
            else
            net_2=d_2-(y_2/4);

            double d_3=Double.parseDouble(tyt5.getText());
            double y_3=Double.parseDouble(tyt6.getText());
            double net_3=0;
            if(d_3+y_3>20)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türkçe 40 soru\n"+
                "Matematik 40 soru \n"+"Sosyal Bilimler 20 soru\n"+
                "Fen Bilimleri 20 soru\n");
            else
            net_3=d_3-(y_3/4);

            double d_4=Double.parseDouble(tyt7.getText());
            double y_4=Double.parseDouble(tyt8.getText());
            double net_4=0;
            if(d_4+y_4>20)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türkçe 40 soru\n"+
                "Matematik 40 soru \n"+"Sosyal Bilimler 20 soru\n"+
                "Fen Bilimleri 20 soru\n");
            else
            net_4=d_4-(y_4/4);

            double topNet=net_1+net_2+net_3+net_4;

            tytTopNet.setText(String.valueOf(topNet));

        }catch(ArithmeticException e){

            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_m_goster1ActionPerformed

    private void m_goster2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_goster2ActionPerformed
        try{
            double d_1=Double.parseDouble(sos1.getText());
            double y_1=Double.parseDouble(sos2.getText());

            double net_1=0;
            if(d_1+y_1>24)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türk Dili ve Edebiyat 24 soru\n"+
                "Tarih-1 10 soru \n"+"Coğrafya-1 6 soru\n");
            else
            net_1=d_1-(y_1/4);

            double d_2=Double.parseDouble(sos3.getText());
            double y_2=Double.parseDouble(sos4.getText());

            double net_2=0;
            if(d_2+y_2>10)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türk Dili ve Edebiyat 24 soru\n"+
                "Tarih-1 10 soru \n"+"Sosyal Coğrafya-1 6 soru\n");
            else
            net_2=d_2-(y_2/4);

            double d_3=Double.parseDouble(sos5.getText());
            double y_3=Double.parseDouble(sos6.getText());

            double net_3=0;
            if(d_3+y_3>6)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Türk Dili ve Edebiyat 24 soru\n"+
                "Tarih-1 10 soru \n"+"Coğrafya-1 6 soru\n");
            else
            net_3=d_3-(y_3/4);

            double topNet=net_1+net_2+net_3;
            topSos1Net.setText(String.valueOf(topNet));
        }
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_m_goster2ActionPerformed

    private void m_goster3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_goster3ActionPerformed
        try{
            double d_1=Double.parseDouble(sos7.getText());
            double y_1=Double.parseDouble(sos8.getText());

            double net_1=0;
            if(d_1+y_1>11)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Tarih-2 11 soru \n"
                +"Coğrafya-2 11 soru\n"+"Felsefe Grubu 12 soru\n"+"Din Kültürü 6 soru\n");
            else
            net_1=d_1-(y_1/4);

            double d_2=Double.parseDouble(sos9.getText());
            double y_2=Double.parseDouble(sos10.getText());
            double net_2=0;
            if(d_2+y_2>11)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Tarih-2 11 soru \n"
                +"Coğrafya-2 11 soru\n"+"Felsefe Grubu 12 soru\n"+"Din Kültürü 6 soru\n");
            else
            net_2=d_2-(y_2/4);

            double d_3=Double.parseDouble(sos11.getText());
            double y_3=Double.parseDouble(sos12.getText());
            double net_3=0;
            if(d_3+y_3>12)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Tarih-2 11 soru \n"
                +"Coğrafya-2 11 soru\n"+"Felsefe Grubu 12 soru\n"+"Din Kültürü 6 soru\n");
            else
            net_3=d_3-(y_3/4);

            double d_4=Double.parseDouble(sos13.getText());
            double y_4=Double.parseDouble(sos14.getText());
            double net_4=0;
            if(d_4+y_4>6)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Tarih-2 11 soru \n"
                +"Coğrafya-2 11 soru\n"+"Felsefe Grubu 12 soru\n"+"Din Kültürü 6 soru\n");
            else
            net_4=d_4-(y_4/4);

            double topNet=net_1+net_2+net_3+net_4;
            topSos2Net.setText(String.valueOf(topNet));
        }
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_m_goster3ActionPerformed

    private void m_goster4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_goster4ActionPerformed
        try{
            double d=Double.parseDouble(mat1.getText());
            double y=Double.parseDouble(mat2.getText());
            double net=0;
            if(d+y>40)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Matematik 40 soru \n");
            else
            net=d-(y/4);

            topMat2Net.setText(String.valueOf(net));}
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_m_goster4ActionPerformed

    private void m_goster5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_goster5ActionPerformed
        try{
            double d_1=Double.parseDouble(fen1.getText());
            double y_1=Double.parseDouble(fen2.getText());
            double net_1=0;
            if(d_1+y_1>14)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Fizik 14 soru\n"+
                "Kimya 13 soru \n"+"Biyoloji 13 soru\n");
            else
            net_1=d_1-(y_1/4);

            double d_2=Double.parseDouble(fen3.getText());
            double y_2=Double.parseDouble(fen4.getText());

            double net_2=0;
            if(d_2+y_2>13)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Fizik 14 soru\n"+
                "Kimya 13 soru \n"+"Biyoloji 13 soru\n");
            else
            net_2=d_2-(y_2/4);

            double d_3=Double.parseDouble(fen5.getText());
            double y_3=Double.parseDouble(fen6.getText());

            double net_3=0;
            if(d_3+y_3>13)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Fizik 14 soru\n"+
                "Kimya 13 soru \n"+"Biyoloji 13 soru\n");
            else
            net_3=d_3-(y_3/4);

            double topNet=net_1+net_2+net_3;
            topFen2Net.setText(String.valueOf(topNet));
        }
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_m_goster5ActionPerformed

    private void m_goster6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_goster6ActionPerformed
        try{
            double d=Double.parseDouble(dil1.getText());
            double y=Double.parseDouble(dil2.getText());
            double net=0;
            if(d+y>80)
            throw new ArithmeticException("Girdiğiniz soru sayılarını kontrol ediniz!\n"+"Dil 80 soru \n");
            else
            net=d-(y/4);

            topDilNet.setText(String.valueOf(net));
        }
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_m_goster6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yksPuanHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yksPuanHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yksPuanHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yksPuanHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yksPuanHesapla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dil1;
    private javax.swing.JTextField dil2;
    private javax.swing.JTextField dil_puan;
    private javax.swing.JTextField dipNot;
    private javax.swing.JTextField fen1;
    private javax.swing.JTextField fen2;
    private javax.swing.JTextField fen3;
    private javax.swing.JTextField fen4;
    private javax.swing.JTextField fen5;
    private javax.swing.JTextField fen6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton m_goster1;
    private javax.swing.JButton m_goster2;
    private javax.swing.JButton m_goster3;
    private javax.swing.JButton m_goster4;
    private javax.swing.JButton m_goster5;
    private javax.swing.JButton m_goster6;
    private javax.swing.JButton m_hesapla;
    private javax.swing.JTextField mat1;
    private javax.swing.JTextField mat2;
    private javax.swing.JTextField say_puan;
    private javax.swing.JTextField sos1;
    private javax.swing.JTextField sos10;
    private javax.swing.JTextField sos11;
    private javax.swing.JTextField sos12;
    private javax.swing.JTextField sos13;
    private javax.swing.JTextField sos14;
    private javax.swing.JTextField sos2;
    private javax.swing.JTextField sos3;
    private javax.swing.JTextField sos4;
    private javax.swing.JTextField sos5;
    private javax.swing.JTextField sos6;
    private javax.swing.JTextField sos7;
    private javax.swing.JTextField sos8;
    private javax.swing.JTextField sos9;
    private javax.swing.JTextField soz_puan;
    private javax.swing.JTextField tm_puan;
    private javax.swing.JLabel topDilNet;
    private javax.swing.JLabel topFen2Net;
    private javax.swing.JLabel topMat2Net;
    private javax.swing.JLabel topSos1Net;
    private javax.swing.JLabel topSos2Net;
    private javax.swing.JTextField tyt1;
    private javax.swing.JTextField tyt2;
    private javax.swing.JTextField tyt3;
    private javax.swing.JTextField tyt4;
    private javax.swing.JTextField tyt5;
    private javax.swing.JTextField tyt6;
    private javax.swing.JTextField tyt7;
    private javax.swing.JTextField tyt8;
    private javax.swing.JLabel tytTopNet;
    private javax.swing.JTextField tyt_puan;
    // End of variables declaration//GEN-END:variables
}
